name: Deploy Honkit to GitHub Pages

on:
  push:
    branches:
      - gitbook
      # 如果有更多版本，添加它们

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Honkit
        run: npm install -g honkit

      - name: Install dependencies (if any)
        run: npm install

      - name: Build GitBook (Honkit)
        run: honkit build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          destination_dir: ${{ github.ref_name }}
          keep_files: true